### ISSUE TITLE
[Solved] Failed to load plugin 'deeps'. Reason: Plugin is compiled with a different interface version than expected.

### ISSUE THREAD

**Issue by nowwhatnapster** [relliko/Deeps#8]
The latest zip file posted does not appear to contain the latest plugin:

Deeps1.06_i4.15.zip

Failed to load plugin 'deeps'. Reason: Plugin is compiled with a different interface version than expected.
Failed to load plugin 'deeps'. Reason: Plugin: 4.15, Expected: 4.16

**Comment by clanofartisans** [comment]
Fixed with PR https://github.com/relliko/Deeps/pull/9

**Comment by relliko** [comment]
Updated the release with @clanofartisans Ashita interface 4.16 binary: https://github.com/relliko/Deeps/releases/tag/v1.06

**Comment by nowwhatnapster** [comment]
Resolved
